ver: "1.0"
rules:
  calendar_1:
    senders: []
    before_ext: [[ask_gpt, {prompt: 'Сформируй json из следующего запроса: \"%event_value%\".
Пример: \"Напомни мне послезавтра про то что мне нужно забрать заказ из интернет магазина после работы\"
Ответ: 
{
  "text": "забрать заказ из магазина",
  "start": {
    "year": 2024,
    "month": 5,
    "day": 19,
    "hour": 18,
    "minute": 30
  },
  "end": {
    "year": 2024,
    "month": 5,
    "day": 19,
    "hour": 18,
    "minute": 45
  }
}
Для указания даты и времени, учитывай, что сейчас %time% %date%'}], json_find, [change_purpose, {new_purpose: "add_event"}]]
    purposes: [pre_add_event]
    acceptors: [calendar]

intent_examples:
  add_event: ["запомни какое-то событие", "запиши что мне надо", "добавь событие о чем-то", "напомни мне об этом позже", "напомни через час полить цветы"]
  get_event: ["напомни когда произойдет это", "скажи когда произойдет что-то", "через сколько дней будет это"]