ver: "1.0"
intent_examples:
  check_update: ["проверь есть ли обновление", "узнай есть ли новая версия", "проверь наличие новой версии", "проверь обновление"]
  update: ["загрузи обновление", "выполни обновление системмы", "скачай свежее обновление", "обновись до последней версии"]